### ISSUE TITLE
Add SQL server support

### ISSUE THREAD

**Issue by lefthandedgoat** [lefthandedgoat/genit#4]
Add an DU for Postgres/SQL and generate different SQL in sql.fs

**Comment by davidpodhola** [comment]
working on [generating Microsoft SQL scripts](https://github.com/davidpodhola/genit/blob/sql4more/src/genit/generator/mssql.fs)

**Comment by davidpodhola** [comment]
Also generating `generated_data_access.fs` goes pretty well, few last bugs to hunt down.

**Comment by lefthandedgoat** [comment]
ok awesome!

if you want i can create a branch, and you can send a PR to it, and I can work on it too this weekend?

**Comment by davidpodhola** [comment]
oops, my reply did not make it to github :-(

yes please, create a branch and I will send a PR to it, thanks!

**Comment by lefthandedgoat** [comment]
Here, you are, thanks!

https://github.com/lefthandedgoat/genit/tree/4-SQLServerSupport

**Comment by davidpodhola** [comment]
[PR](https://github.com/lefthandedgoat/genit/pull/40)

**Comment by lefthandedgoat** [comment]
@davidpodhola I see that it generates code that uses the FSharp.Data.SqlClient type provider.  I have used it a lot and really really like it.  Do you think its ok if I at first use regular ado.net ?  Since types are already created and mapping code is necessary for both ways? You would compile time query checking though.

**Comment by lefthandedgoat** [comment]
Also I am going to remove the 'References' feature for now and focus on just SQL server, then we can add that part next.

**Comment by davidpodhola** [comment]
Of course! Please change as you wish. I just like the `Option` for `NULL` and stuff much more (we are using `FSharp.Data.SqlClient` in production).

**Comment by lefthandedgoat** [comment]
Ok I will keep in mind to use option for anything that is not required, expect maybe strings, since they can be null in F#.  Not sure, will think on that.

**Comment by davidpodhola** [comment]
Yes, we also do not use `string option `. But feel free to do whatever changes needed. I really think what you started is great :-)

**Comment by lefthandedgoat** [comment]
Note to self: collapse ado helpers to one file and switch postgres to use IDataReader if possible to reduce copy/pasta

**Comment by lefthandedgoat** [comment]
Also make sure that it creates proper names for SQL Server columns

**Comment by lefthandedgoat** [comment]
Last bit of todo:

  * Refactor all the ado helper into one multi module file
  * Clean up the psql and mssql files and remove common stuff
  * make the fake task use the correctly sql commands for sql server

**Comment by lefthandedgoat** [comment]
@davidpodhola 
I think I finished it!!

Thank you for all of your contribs!  If you would like to test it before I pull to master that would be great!

2 things to note:

https://github.com/lefthandedgoat/genit/blob/4-SQLServerSupport/build.fsx#L148-L154

and 

https://github.com/lefthandedgoat/genit/blob/4-SQLServerSupport/src/genit/generator/mssql.fs#L282

You may need to change those from `.\SQLEXPRESS` to whatever is correct for you.  I may change the dsl to require you give that since there is such a variety of possibilities on sql server.

I also had to remove the stuff for Many to Many and Child relationships (I have a todo for 1 to many).

I made postgres work with `option` type data like you added (thanks!), and fixed it all throughout the UI.

With the simplification of using ADO.net instead of a type provider I was also able to reduce the amount of specific code in mssql.fs and psql.fs

Branch: `4-SQLServerSupport`

Thanks again!! and I will be making you contrib.  PR to master is still preferred, but this will let you make feature branches and stufff yourself!

**Comment by lefthandedgoat** [comment]
Merged to master

**Comment by davidpodhola** [comment]
back from vacations, ready to have a look, thanks! :-)
