### ISSUE TITLE
No phone length validation

### ISSUE THREAD

**Issue by isaacabraham** [lefthandedgoat/genit#51]
If you create a phone number longer than that supported by the database (15 chars) you get a SQL constraint exception. This is definitely better than simply truncating the text, but it would be preferable to have a proper validation error.

**Comment by lefthandedgoat** [comment]
Thanks, I will add some more validations today!

**Comment by isaacabraham** [comment]
Basically I will raise one issue for every PR I submit ;-)

**Comment by lefthandedgoat** [comment]
Totally fine.  Issues are good with me, PRs are great!

**Comment by lefthandedgoat** [comment]
Added, thanks again
